// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXRMslcPbZJKAhziyMlUARPkQ7uLpoikc',
    appId: '1:634982029029:web:af2c72551bf5153555660c',
    messagingSenderId: '634982029029',
    projectId: 'calendar-todo-o2c30q',
    authDomain: 'calendar-todo-o2c30q.firebaseapp.com',
    storageBucket: 'calendar-todo-o2c30q.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdHww7ZTlYBFODz-wGuVjEQo04ac6-CAw',
    appId: '1:634982029029:android:7b03da1f44dd07ab55660c',
    messagingSenderId: '634982029029',
    projectId: 'calendar-todo-o2c30q',
    storageBucket: 'calendar-todo-o2c30q.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfrEzBA-DGn5qhxuEqN0auHTuebXOSSbA',
    appId: '1:634982029029:ios:8e82a5285021c22655660c',
    messagingSenderId: '634982029029',
    projectId: 'calendar-todo-o2c30q',
    storageBucket: 'calendar-todo-o2c30q.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfrEzBA-DGn5qhxuEqN0auHTuebXOSSbA',
    appId: '1:634982029029:ios:8e82a5285021c22655660c',
    messagingSenderId: '634982029029',
    projectId: 'calendar-todo-o2c30q',
    storageBucket: 'calendar-todo-o2c30q.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
}